### ISSUE TITLE
Modify key does not support combining characters

### ISSUE THREAD

**Issue by jose1711** [dessalines/thumb-key#1394]
### Steps to reproduce

Configure the following in Modify key section:
```
ENMessagEase:
  main:
    key0_0:
      topLeft:
        text: ◌́
```
Type `i`, followed by top-left swipe on the modified key.

### Expected behavior

`i` turns into `í`.

### Actual behavior

You get `◌́` instead.

### version of the program

4.0.33

### Android version

Android 14

### Device

Galaxy A52

### Acknowledgements

- [x] I have written a short but informative title.
- [x] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [x] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [x] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [x] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [x] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
cc @Toldry

**Comment by Toldry** [comment]
I tried this and it worked:

```yaml
ENMessagEase:
  main:
    key0_0:
      topLeft:
        text: "\u0301"
        displayText: "◌́"
```

I don't know why doing it with just `text: "◌́"` doesn't work. I found this solution by looking at `EuropeThumbKey.kt` and saw this code there:

```kotlin
bottomRight = KeyC("\u0301", displayText = "◌́"),
```

@dessalines do you know why it was coded this way?
