### ISSUE TITLE
Feature Request: Add moveUp/moveDown actions to YAML key customization

### ISSUE THREAD

**Issue by hazgon** [dessalines/thumb-key#1418]
## Problem Description

In MessageEase, it was possible to move the cursor up and down using swipes:
- Swiping up from the "i" key = move cursor up
- Swiping down from the "s" key = move cursor down

In Thumb-Key, this functionality was removed from regular layouts (issue #195) due to accidental triggers when swiping on the spacebar. It is currently only available in programming layouts.

## Proposed Solution

Add new actions to the YAML key customization (`Modify keys`):
- `moveUp` - to move the cursor up one line
- `moveDown` - to move the cursor down one line

This would allow users to assign these actions to their preferred keys, for example:
```yaml
ENThumbKey:
  main:
    key0_1:  # "i" key
      top:
        keyAction: moveUp
    key2_1:  # "s" key
      bottom:
        keyAction: moveDown
```

## Justification

1.  **Preserving MessageEase user habits**: Many users are accustomed to this functionality and want to keep it.
2.  **Customization flexibility**: Users will be able to choose which keys and swipe directions to use.
3.  **Avoiding accidental triggers**: Unlike placement on the spacebar, users can choose locations less prone to accidental triggers.
4.  **API consistency**: `Left` and `Right` actions already exist; it's logical to add `Up` and `Down`.

Currently available `keyAction`s only include horizontal cursor movement (`Left`, `Right`), but not vertical.

### Acknowledgements

- [x] I have written a short but informative title.
- [x] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [x] I have checked through the app settings for my feature.
- [x] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [x] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [x] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [x] I will fill out all of the requested information in this form.

**Comment by dafiish** [comment]
I would like that too. Instead of "moveUp" and "moveDown," we could use "Up" and "Down" to match existing "Left" and "Right". Besides that, key actions like "ToggleShiftMode," "ToggleCurrentWordCapitalization," "ShiftKeyboard," "SwitchKeyboard" or "Delete" are also missing.

**Comment by dessalines** [comment]
cc @Toldry

**Comment by Toldry** [comment]
My laptop is currently being repaired so I can't implement anything. But I will note that once the `MoveUp` and `MoveDown` actions are implemented, then adding them as actions that can be set via the key modification YAML should be trivial.

**Comment by molinohub** [comment]
Hi, I am new here. Have used MessagEase for years with my own tweaks to be able to type faster. A stupid newbee question and it would be over-kill to open a new request for it : the documentation here on github and in f-droid only states how to edit the YAML config file, contentwise, but not where in the file system thumb-key would look for a file with that content and what naminq sceme it needs. This short text took me 5 instead of 1 min to write. And I had to look at the keyboard! ugh! Started using thumb-key today. 
I really appreciate your work !
I even join patreon 10 min ago to supprt you.

**Comment by alerque** [comment]
> how to edit the YAML config file, contentwise, but not where in the file system thumb-key would look for a file with that content and what naminq sceme it needs

You don't need a file at all or anywhere on the system, what you need is the YAML content pasted into the relevant setting text box. You can save and edit your YAML wherever you like in whatever editor you want, then just copy/paste it into the text box. You can also edit it after pasting (and changes take effect right away).

**Comment by molinohub** [comment]
> > how to edit the YAML config file, contentwise, but not where in the file system thumb-key would look for a file with that content and what naminq sceme it needs
> 
> You don't need a file at all or anywhere on the system, what you need is the YAML content pasted into the relevant setting text box. You can save and edit your YAML wherever you like in whatever editor you want, then just copy/paste it into the text box. You can also edit it after pasting (and changes take effect right away).

Wow, cool, this works like a charm! Thx for the fast answer but still it would help if you/sb w replace the reference to a ´config file´ with ´text box in the Modify keys settings section´ or similar in the documentation here and where ever.

Keep up the good spirit !

**Comment by mkeller** [comment]
https://github.com/dessalines/thumb-key?tab=readme-ov-file#example-3 already mentions 

keyAction: Top/Bottom, but they are marked as error in the yaml editor.

Up and Down would be better names anyway.

**Comment by dessalines** [comment]
Are you updated to the most recent release?

**Comment by mkeller** [comment]
Oh, sorry, I assumed F-Droid would offer the latest version, but apparently, it's stuck at 5.0.3.

In 5.0.7 from IzzyOnDroid, it works. Here's my layout fix for German MessagEase Symbols:

```
DEMessagEaseSymbols:
  main:
    key0_0: { longPress: { text: "1" } }
    key0_1: { longPress: { text: "2" } }
    key0_2: { longPress: { text: "3" }, top: { keyAction: Top } }
    key1_0: { longPress: { text: "4" } }
    key1_1: { longPress: { text: "5" } }
    key1_2: { longPress: { text: "6" } }
    key2_0: { longPress: { text: "7" } }
    key2_1: { longPress: { text: "8" } }
    key2_2: { longPress: { text: "9" }, bottom: {keyAction: Bottom } }
    key3_0: { longPress: { text: "0" } }
```

All MessagEase layouts shoud support these keys by default, for compatibility.
