### ISSUE TITLE
[Suggestion] Use GitHub Issue forms instead of issue templates

### ISSUE THREAD

**Issue by asdkant** [dessalines/thumb-key#662]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

# Description

GitHub has a feature called [Issue Forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms), which lets you configure forms for people opening new issues instead of having issue templates.

I've seen it used in [TachiyomiJ2K](https://github.com/Jays2Kings/tachiyomiJ2K) successfully, and cribbed [their configs](https://github.com/Jays2Kings/tachiyomiJ2K/tree/master/.github/ISSUE_TEMPLATE) for my fork of thumb-key, here's the important stuff mostly as I used it, feel free to take it for thumb-key and modify it as you see fit:

`.github/ISSUE_TEMPLATE/config.yml`
```yaml
blank_issues_enabled: false
# contact_links:
#   - name: 💬 Discussions
#     url: https://github.com/user/repo/discussions
#     about: If you want to start a conversation, go to the discussions section
```

`.github/ISSUE_TEMPLATE/feature_request.yml`
```yaml
name: 🌟 Feature request
description: Suggest a feature to improve the app
labels: [feature]
body:

  - type: textarea
    id: feature-description
    attributes:
      label: Describe your suggested feature
      description: How can the app be improved?
      placeholder: |
        Example:
          "It should work like this..."
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Read this carefully, we will close and ignore your issue if you skimmed through this.
      options:
        - label: >-
            I have searched the existing issues and this is a new one, **NOT** a duplicate or related to another open issue.
          required: true
        - label: >-
            This is a **single** feature request, 
            in case of multiple feature requests I will open a separate issue for each one
            (they can always link to each other if related)
          required: true
        - label: >-
            This is not a question or a discussion, in which case I should have gone to the 
            [Discussions](https://github.com/user/repo/discussions) section
          required: true
        - label: I have written a short but informative title.
          required: true
        # - label: I have updated the app **[the latest version](https://github.com/user/repo/releases/latest)**.
        #   required: true
        - label: I have checked through the app settings for my feature.
          required: true
        - label: I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
        - label: I will fill out all of the requested information in this form.
          required: true
```

`.github/ISSUE_TEMPLATE/issue_report.yml`
```yaml
name: 🐞 Issue report
description: Report an issue or bug
labels: [bug]
body:
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Provide an example of the issue.
      placeholder: |
        Example:
          1. First step
          2. Second step
          3. Issue here
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Explain what you should expect to happen.
      placeholder: |
        Example:
          "This should happen..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Explain what actually happens.
      placeholder: |
        Example:
          "This happened instead..."
    validations:
      required: true

  # - type: textarea
  #   id: crash-logs
  #   attributes:
  #     label: Crash logs
  #     description: |
  #       If you're experiencing crashes, share the crash logs from **More → Settings → Advanced** then press **Dump crash logs**.
  #     placeholder: |
  #       You can paste the crash logs in pure text or upload it as an attachment.

  # - type: input
  #   id: version
  #   attributes:
  #     label: version of the program
  #     description: "."
  #     placeholder: |
  #       Example: "1.5.8"
  #   validations:
  #     required: true

  - type: input
    id: android-version
    attributes:
      label: Android version
      description: You can find this somewhere in your Android settings.
      placeholder: |
        Example: "Android 14"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      description: List your device and model.
      placeholder: |
        Example: "Google Pixel 8"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Read this carefully, I will close and ignore your issue if you skimmed through this.
      options:
        - label: >-
            I have searched the existing issues and this is a new one, **NOT** a duplicate or related to another open issue.
          required: true
        - label: >-
            This is not a question or a discussion, in which case I should have gone to the 
            [Discussions](https://github.com/user/repo/discussions) section
          required: true
        - label: >-
            This is a **single** bug report, 
            in case of multiple bugs I will open a separate issue for each one 
            (they can always link to each other if related)
          required: true
        - label: I have written a short but informative title.
          required: true
        # - label: I have updated the app **[the latest version](https://github.com/user/repo/releases/latest)**.
        #   required: true
        - label: I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
        - label: I have filled out all of the requested information in this form.
          required: true
```
